/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "tutorial" }],
  jsPackageSidebar: [{ type: "autogenerated", dirName: "js-package" }],
  javaPackageSidebar: [{ type: "autogenerated", dirName: "java-package" }],
  javaScriptSidebar: [{type: "autogenerated", dirName: "js"}],
  toolSidebar: [{ type: "autogenerated", dirName: "devTool" }],
  installSidebar: [{ type: "autogenerated", dirName: "install" }]


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
